/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_alberthgodoy;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author godoy
 */
public class Lab8P2_AlberthGodoy extends javax.swing.JFrame {
    
    private ArrayList<Universos> universos = new ArrayList();
    private ArrayList<seresVivos> seresVivos = new ArrayList();
    private administradorUniversos adminTodoUniverso = new administradorUniversos("./Archivo/TodoUniversos/todoUniverso.cheemz");
    private administradorUniversos adminTodoSerVivo = new administradorUniversos("./Archivo/TodoSerVivo/todoSerVivo.dame10puntos");
    private DefaultComboBoxModel<Universos> jComboUniversos = new DefaultComboBoxModel();
    private DefaultComboBoxModel<seresVivos> jComboSeresVivos = new DefaultComboBoxModel();

    /**
     * Creates new form Lab8P2_AlberthGodoy
     */
    public Lab8P2_AlberthGodoy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane_Inicio = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_NombreUniverso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NombreserVivo = new javax.swing.JTextField();
        jComboBox_Universo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_SerVivo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField_CantSeresVivos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_iDSerVivo = new javax.swing.JTextField();
        jSpinner_PoderSerVivo = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_AgeSerVivo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_Raza = new javax.swing.JComboBox<>();
        jButton_CrearUniverso = new javax.swing.JButton();
        jButton_CrearSerVivo = new javax.swing.JButton();
        jButton_GuardarDatosSeresVivos = new javax.swing.JButton();
        jButton_CargarDatosUniverso = new javax.swing.JButton();
        jButton_GuardarDatosUniverso = new javax.swing.JButton();
        jButton_CargarDatosSerVivo = new javax.swing.JButton();
        jButton_AgregarServivoAUniverso = new javax.swing.JButton();
        jProgressBar_CargarDatoUniverso = new javax.swing.JProgressBar();
        jProgressBar_CargarDatoSerVivo = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_NombreUniversoModificar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_CantSerVivosModificar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox_RazaModificar = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jTextField_AgeServVivoModificar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_iDSerVivoModificar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_NombreserVivoModificar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jComboBox_UniversoModificar = new javax.swing.JComboBox<>();
        jComboBox_SerVivoModificar = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_ModificarUniverso = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Crear Universos");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cantidad de Seres Vivos");

        jComboBox_Universo.setModel((DefaultComboBoxModel)jComboUniversos);

        jLabel4.setText("Universo");

        jLabel5.setText("Seres Vivo a agregar");

        jComboBox_SerVivo.setModel((DefaultComboBoxModel)jComboSeresVivos);

        jLabel6.setText("Crear Seres Vivos");

        jLabel7.setText("Nombre");

        jLabel8.setText("ID");

        jSpinner_PoderSerVivo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel9.setText("Poder");

        jLabel10.setText("Años");

        jTextField_AgeSerVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeSerVivoActionPerformed(evt);
            }
        });

        jLabel11.setText("Raza");

        jComboBox_Raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));

        jButton_CrearUniverso.setText("Crear Universo");
        jButton_CrearUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearUniversoMouseClicked(evt);
            }
        });

        jButton_CrearSerVivo.setText("Crear Seres Vivos");
        jButton_CrearSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearSerVivoMouseClicked(evt);
            }
        });

        jButton_GuardarDatosSeresVivos.setText("Guardar Datos Ser Vivo");
        jButton_GuardarDatosSeresVivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GuardarDatosSeresVivosMouseClicked(evt);
            }
        });
        jButton_GuardarDatosSeresVivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarDatosSeresVivosActionPerformed(evt);
            }
        });

        jButton_CargarDatosUniverso.setText("Cargar Datos Universo");
        jButton_CargarDatosUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CargarDatosUniversoMouseClicked(evt);
            }
        });

        jButton_GuardarDatosUniverso.setText("Guardar Datos Universo");
        jButton_GuardarDatosUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GuardarDatosUniversoMouseClicked(evt);
            }
        });
        jButton_GuardarDatosUniverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarDatosUniversoActionPerformed(evt);
            }
        });

        jButton_CargarDatosSerVivo.setText("Cargar Datos Ser Vivo");
        jButton_CargarDatosSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CargarDatosSerVivoMouseClicked(evt);
            }
        });

        jButton_AgregarServivoAUniverso.setText("Agregar Ser vivo al universo");
        jButton_AgregarServivoAUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AgregarServivoAUniversoMouseClicked(evt);
            }
        });

        jProgressBar_CargarDatoUniverso.setMaximum(universos.size());

        jProgressBar_CargarDatoSerVivo.setMaximum(universos.size());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_NombreserVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_iDSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_CantSeresVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSpinner_PoderSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_AgeSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBox_Raza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton_CrearSerVivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jButton_CrearUniverso)
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton_GuardarDatosUniverso))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_NombreUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox_Universo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_AgregarServivoAUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_GuardarDatosSeresVivos)
                                    .addComponent(jButton_CargarDatosSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(145, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_SerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(409, 409, 409)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_CargarDatosUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar_CargarDatoUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar_CargarDatoSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_NombreUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Universo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_AgregarServivoAUniverso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_SerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_CantSeresVivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_NombreserVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_PoderSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextField_iDSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_AgeSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_CrearSerVivo)
                                            .addComponent(jButton_CargarDatosSerVivo)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jButton_GuardarDatosUniverso))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton_CrearUniverso)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_GuardarDatosSeresVivos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_CargarDatosUniverso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar_CargarDatoUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar_CargarDatoSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane_Inicio.addTab("Crear Universos", jPanel1);

        jLabel12.setText("Modificar Universos");

        jLabel13.setText("Nombre");

        jLabel14.setText("Cantidad de Seres Vivos");

        jLabel15.setText("Universo");

        jLabel17.setText("Raza");

        jComboBox_RazaModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));

        jLabel18.setText("Poder");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jTextField_AgeServVivoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeServVivoModificarActionPerformed(evt);
            }
        });

        jLabel19.setText("Años");

        jLabel20.setText("ID");

        jLabel21.setText("Nombre");

        jLabel22.setText("Crear Seres Vivos");

        jButton6.setText("Modificar Ser Vivo");

        jComboBox_UniversoModificar.setModel((DefaultComboBoxModel)jComboUniversos);

        jComboBox_SerVivoModificar.setModel((DefaultComboBoxModel)jComboSeresVivos);

        jLabel23.setText("Ser Vivo");

        jButton1.setText("Seleccionar Universo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Seleccionar Ser Vivo");

        jButton_ModificarUniverso.setText("Modificar Universo");
        jButton_ModificarUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ModificarUniversoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_NombreUniversoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox_UniversoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel14)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_NombreserVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_iDSerVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_CantSerVivosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField_AgeServVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(jComboBox_RazaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jButton_ModificarUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(98, 336, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox_SerVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NombreUniversoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_UniversoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CantSerVivosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ModificarUniverso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_NombreserVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_SerVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(12, 12, 12)
                                .addComponent(jTextField_iDSerVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_AgeServVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_RazaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane_Inicio.addTab("Modificar Universos", jPanel2);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane_Inicio.addTab("Eliminar Registros de Seres Vivos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_Inicio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_Inicio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_AgeServVivoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeServVivoModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeServVivoModificarActionPerformed

    private void jButton_AgregarServivoAUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AgregarServivoAUniversoMouseClicked
        //Agregar ser vivo a universo
        seresVivos serVivoSelect = (seresVivos) jComboBox_SerVivo.getSelectedItem();
        Universos universoSelect = (Universos) jComboBox_Universo.getSelectedItem();
        try {
            for (int i = 0; i < universos.size(); i++) {
                Universos universoAverificar = universos.get(i);
                if (universoAverificar.getSeresVivos().contains(serVivoSelect)) {
                    throw new Exception("Ya esta ese ser vivo en este universo");
                }
            }
            universoSelect.getSeresVivos().add(serVivoSelect);
            JOptionPane.showMessageDialog(this, String.format("%s ha sido agregado a %s", universoSelect.getNombre(), serVivoSelect.getNombre()), "Exito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.format("%s%n", e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_AgregarServivoAUniversoMouseClicked

    private void jButton_CargarDatosSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CargarDatosSerVivoMouseClicked
        //Cargar Datos Ser Vivo
        //Cargar todo
        adminTodoSerVivo.cargarArchivoSerVivo();
        //Agregarlo en el arraylist
        seresVivos = adminTodoSerVivo.getAdminserVivo();
        System.out.println(seresVivos);
        //Agregar al combobox
        jComboSeresVivos = new DefaultComboBoxModel();
        for (int i = 0; i < seresVivos.size(); i++) {
            jComboSeresVivos.addElement(seresVivos.get(i));
        }
        //Barra de progreso
        jProgressBar_CargarDatoSerVivo.setValue(0);
        jProgressBar_CargarDatoSerVivo.setMaximum(seresVivos.size());
        progressBar JBarraUniverso = new progressBar(jProgressBar_CargarDatoSerVivo);
        try {
            JBarraUniverso.start();
        } catch (Exception e) {
        }
        jComboBox_SerVivo.setModel((DefaultComboBoxModel) jComboSeresVivos);
        jComboBox_SerVivoModificar.setModel((DefaultComboBoxModel) jComboSeresVivos);
        JOptionPane.showMessageDialog(this, "Archivos cargados", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_CargarDatosSerVivoMouseClicked

    private void jButton_GuardarDatosUniversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarDatosUniversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GuardarDatosUniversoActionPerformed

    private void jButton_GuardarDatosUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GuardarDatosUniversoMouseClicked
        //Guardar Datos Universo
        //Guardar Todo
        if (universos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay universos para guardar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //Guardar Todo
            adminTodoUniverso.setAdminUniversos(universos);
            adminTodoUniverso.escribirArchivoUniversos();
            System.out.println("Todo =" + adminTodoUniverso.getAdminUniversos());
            //Guardar Individual
            for (int i = 0; i < universos.size(); i++) {
                Universos univerSelected = universos.get(i);
                administradorUniversos adminUniversoIndividual = new administradorUniversos("./Archivo/Universos/" + univerSelected.getNombre() + ".nose");
                adminUniversoIndividual.getAdminUniversosIndividual().add(univerSelected);
                adminUniversoIndividual.escribirArchivoUniversoIndividual();
                System.out.printf("[%d]:%s%n", i, univerSelected);
            }
            
            JOptionPane.showMessageDialog(this, "Datos Guardados", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton_GuardarDatosUniversoMouseClicked

    private void jButton_CargarDatosUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CargarDatosUniversoMouseClicked
        //Cargar datos Universo
        //Cargar todo
        adminTodoUniverso.cargarArchivoUniverso();
        //Agregarlo en el arraylist
        universos = adminTodoUniverso.getAdminUniversos();
        System.out.println(universos);
        //Agregar al combobox
        jComboUniversos = new DefaultComboBoxModel();
        for (int i = 0; i < universos.size(); i++) {
            jComboUniversos.addElement(universos.get(i));
        }
        //Barra de progreso
        jProgressBar_CargarDatoUniverso.setValue(0);
        jProgressBar_CargarDatoUniverso.setMaximum(universos.size());
        progressBar JBarraUniverso = new progressBar(jProgressBar_CargarDatoUniverso);
        try {
            JBarraUniverso.start();
        } catch (Exception e) {
        }
        jComboBox_Universo.setModel((DefaultComboBoxModel) jComboUniversos);
        jComboBox_UniversoModificar.setModel((DefaultComboBoxModel) jComboUniversos);
        JOptionPane.showMessageDialog(this, "Archivos cargados", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_CargarDatosUniversoMouseClicked

    private void jButton_GuardarDatosSeresVivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarDatosSeresVivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GuardarDatosSeresVivosActionPerformed

    private void jButton_GuardarDatosSeresVivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GuardarDatosSeresVivosMouseClicked
        //Guardar Datos Seres vivos
        //Guardar Todo
        if (seresVivos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay universos para guardar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //Guardar Todo
            adminTodoSerVivo.setAdminserVivo(seresVivos);
            adminTodoSerVivo.escribirArchivoserVivo();
            System.out.println("Todo =" + adminTodoSerVivo.getAdminserVivo());
            //Guardar Individual
            for (int i = 0; i < seresVivos.size(); i++) {
                seresVivos servivoSelected = seresVivos.get(i);
                administradorUniversos adminSerVivoIndividual = new administradorUniversos("./Archivo/SerVivo/" + servivoSelected.getNombre() + ".nose");
                adminSerVivoIndividual.getAdminserVivoIndividual().add(servivoSelected);
                adminSerVivoIndividual.escribirArchivoserVivoIndividual();
                System.out.printf("[%d]:%s%n", i, servivoSelected);
            }
            
            JOptionPane.showMessageDialog(this, "Datos Guardados", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_GuardarDatosSeresVivosMouseClicked

    private void jButton_CrearSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearSerVivoMouseClicked
        //Crear serVivo
        try {
            if (universos.isEmpty()) {
                throw new Exception("No puedes agregar sin tener universos");
            } else {
                String nombre = "";
                String iD = "";
                if (universos.isEmpty()) {
                    //Agregar ID
                    iD = jTextField_iDSerVivo.getText();
                } else {
                    for (int i = 0; i < seresVivos.size(); i++) {
                        if (jTextField_iDSerVivo.getText().equals(seresVivos.get(i).getiD())) {
                            throw new Exception("Ya esta ese ID");
                        } else {
                            iD = jTextField_iDSerVivo.getText();
                        }
                        
                    }
                    if (universos.isEmpty()) {
                        nombre = jTextField_NombreserVivo.getText();
                    } else {
                        for (int i = 0; i < seresVivos.size(); i++) {
                            if (jTextField_NombreserVivo.getText().equals(seresVivos.get(i).getNombre())) {
                                throw new Exception("Ya esta el nombre del ser vivo");
                            }
                        }
                        nombre = jTextField_NombreserVivo.getText();
                    }
                    int poderEscala = (int) jSpinner_PoderSerVivo.getValue();
                    int age = Integer.parseInt(jTextField_AgeSerVivo.getText());
                    String procedencia = ((Universos) jComboBox_Universo.getSelectedItem()).getNombre();
                    String raza = jComboBox_Raza.toString();
                    //Agregar al ArrayList
                    seresVivos serVivo = new seresVivos(nombre, iD, poderEscala, age, procedencia, raza);
                    seresVivos.add(serVivo);
                    //Agregar al comboBox
                    jComboSeresVivos.addElement(serVivo);
                    JOptionPane.showMessageDialog(this, String.format("Ser Vivo %s creado%n", nombre), "Creado", JOptionPane.INFORMATION_MESSAGE);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.format("%s%n", e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CrearSerVivoMouseClicked

    private void jButton_CrearUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearUniversoMouseClicked
        //Crear un universos
        try {
            String nombre = "";
            if (universos.isEmpty()) {
                nombre = jTextField_NombreUniverso.getText();
            } else {
                for (int i = 0; i < universos.size(); i++) {
                    Universos universoSelec = universos.get(i);
                    if (universoSelec.getNombre().equals(jTextField_NombreUniverso.getText())) {
                        throw new Exception("Ya hay un universo con ese nombre");
                    }
                    
                }
                nombre = jTextField_NombreUniverso.getText();
            }
            
            int cantSeresVivos = Integer.parseInt(jTextField_CantSeresVivos.getText());
            Universos universo = new Universos(nombre, cantSeresVivos);
            //Agregar Al ComboBox
            jComboUniversos.addElement(universo);
            //Agregar al arrayList
            universos.add(universo);
            //Limpiar
            jTextField_NombreUniverso.setText("");
            jTextField_CantSeresVivos.setText("");
            JOptionPane.showMessageDialog(this, String.format("Universo %s creado%n", nombre), "Creado", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, String.format("%s%n", e), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.format("%s%n", e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CrearUniversoMouseClicked

    private void jTextField_AgeSerVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeSerVivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeSerVivoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //Modificar Universo
        Universos universoSelect = (Universos) jComboBox_UniversoModificar.getSelectedItem();
        jTextField_NombreUniversoModificar.setText(universoSelect.getNombre());
        jTextField_CantSerVivosModificar.setText(Integer.toString(universoSelect.getCantSeresVivos()));
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton_ModificarUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ModificarUniversoMouseClicked
        //Modificar universo
         Universos universoSelect = (Universos) jComboBox_UniversoModificar.getSelectedItem();
        try {
            String nombre = "";
            if (universos.isEmpty()) {
                nombre = jTextField_NombreUniversoModificar.getText();
            } else {
                for (int i = 0; i < universos.size(); i++) {
                    Universos universoSelec = universos.get(i);
                    if (universoSelec.getNombre().equals(jTextField_NombreUniverso.getText())) {
                        throw new Exception("Ya hay un universo con ese nombre");
                    }
                    
                }
                nombre = jTextField_NombreUniversoModificar.getText();
            }
            
            int cantSeresVivos = Integer.parseInt(jTextField_CantSerVivosModificar.getText());
            //Modificar el universo
            for (int i = 0; i < universos.size(); i++) {
                Universos universoaMoficiar = universos.get(i);
                if (universoaMoficiar.equals(universoSelect)) {
                    universoaMoficiar.setNombre(nombre);
                    universoaMoficiar.setCantSeresVivos(cantSeresVivos);
                }
            }
            //Modificar en el archivo
            adminTodoUniverso.setAdminUniversos(universos);
            adminTodoUniverso.escribirArchivoUniversos();
            JOptionPane.showMessageDialog(this, String.format("Universo %s Modificado%n", universoSelect.getNombre()), "Creado", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, String.format("%s%n", e), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.format("%s%n", e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_ModificarUniversoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_AlberthGodoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab8P2_AlberthGodoy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_AgregarServivoAUniverso;
    private javax.swing.JButton jButton_CargarDatosSerVivo;
    private javax.swing.JButton jButton_CargarDatosUniverso;
    private javax.swing.JButton jButton_CrearSerVivo;
    private javax.swing.JButton jButton_CrearUniverso;
    private javax.swing.JButton jButton_GuardarDatosSeresVivos;
    private javax.swing.JButton jButton_GuardarDatosUniverso;
    private javax.swing.JButton jButton_ModificarUniverso;
    private javax.swing.JComboBox<String> jComboBox_Raza;
    private javax.swing.JComboBox<String> jComboBox_RazaModificar;
    private javax.swing.JComboBox<String> jComboBox_SerVivo;
    private javax.swing.JComboBox<String> jComboBox_SerVivoModificar;
    private javax.swing.JComboBox<String> jComboBox_Universo;
    private javax.swing.JComboBox<String> jComboBox_UniversoModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar_CargarDatoSerVivo;
    private javax.swing.JProgressBar jProgressBar_CargarDatoUniverso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner_PoderSerVivo;
    private javax.swing.JTabbedPane jTabbedPane_Inicio;
    private javax.swing.JTextField jTextField_AgeSerVivo;
    private javax.swing.JTextField jTextField_AgeServVivoModificar;
    private javax.swing.JTextField jTextField_CantSerVivosModificar;
    private javax.swing.JTextField jTextField_CantSeresVivos;
    private javax.swing.JTextField jTextField_NombreUniverso;
    private javax.swing.JTextField jTextField_NombreUniversoModificar;
    private javax.swing.JTextField jTextField_NombreserVivo;
    private javax.swing.JTextField jTextField_NombreserVivoModificar;
    private javax.swing.JTextField jTextField_iDSerVivo;
    private javax.swing.JTextField jTextField_iDSerVivoModificar;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
